name: FairCut Daily Batch Pipeline

on:
  schedule:
    # Exécution automatique tous les matins à 6h00 UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  run-batch:
    runs-on: ubuntu-latest
    permissions:
        contents: write # <--- PERMISSION D'ÉCRITURE REQUISE
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Prediction Batch
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          python src/predict.py

      - name: Run Drift Monitoring
        id: monitoring
        continue-on-error: true
        run: |
          python src/monitoring.py

      - name: Re-train Challenger Model V2 (If Drift Detected)
        if: steps.monitoring.outcome == 'failure'
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          python src/train.py

      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/processed/ data/monitoring/ models/
          git status
          git diff-index --quiet HEAD || git commit -m "chore(data): auto-update daily predictions, drift report & model version"
          git push